version: 2.1

executors:
  tap_tester:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester

jobs:
  build:
    executor: tap_tester
    steps:
      - run: echo 'CI done'

workflows:
  commit: &commit_jobs
    jobs:
      - build:
          context:
            - circleci-user
