version: 2.1

jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
    steps:
      - checkout

      - run:
          name: "Setup virtual env and install tap-amplitude"
          command: |
            python3 -m venv /usr/local/share/virtualenvs/tap-amplitude
            source /usr/local/share/virtualenvs/tap-amplitude/bin/activate
            pip install -U "pip==22.2.2" "setuptools==65.3.0"
            pip install .[dev]

      - run:
          name: "Run Pylint"
          command: |
            source /usr/local/share/virtualenvs/tap-amplitude/bin/activate
            pip install pylint
            pylint tap_amplitude -d C,R,W || true

      - run:
          name: "Run Unit Tests"
          command: |
            source /usr/local/share/virtualenvs/tap-amplitude/bin/activate
            pip install nose coverage

            # Hardcoded Snowflake test environment variables
            export TAP_SNOWFLAKE_USERNAME="TESTDEV"
            export TAP_SNOWFLAKE_PASSWORD="Test@123456789"
            export TAP_SNOWFLAKE_ACCOUNT="UABYGEJ-WN20681"
            export TAP_SNOWFLAKE_DATABASE="SNOWFLAKE_LEARNING_DB"
            export TAP_SNOWFLAKE_WAREHOUSE="COMPUTE_WH"

            mkdir -p test_output
            nosetests --with-coverage --cover-erase --cover-package=tap_amplitude --cover-html-dir=htmlcov tests | tee test_output/report.xml
            coverage html

      - store_test_results:
          path: test_output

      - store_artifacts:
          path: htmlcov

      - run:
          name: "Run Integration Tests"
          no_output_timeout: 30m
          command: |
            # Hardcoded Snowflake test environment variables
            export TAP_SNOWFLAKE_USERNAME="TESTDEV"
            export TAP_SNOWFLAKE_PASSWORD="Test@123456789"
            export TAP_SNOWFLAKE_ACCOUNT="UABYGEJ-WN20681"
            export TAP_SNOWFLAKE_DATABASE="SNOWFLAKE_LEARNING_DB"
            export TAP_SNOWFLAKE_WAREHOUSE="COMPUTE_WH"

            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/tap_tester_sandbox ./dev_env.sh
            source ./dev_env.sh
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            run-test --tap tap-amplitude tests

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user

  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
