version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python=3.9 /usr/local/share/virtualenvs/tap-amplitude
            source /usr/local/share/virtualenvs/tap-amplitude/bin/activate
            uv pip install -U pip setuptools
            uv pip install .[dev]
      - run:
          name: 'Integration Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/tap_tester_sandbox dev_env.sh
            source dev_env.sh
            run-test --tap=tap-amplitude tests
workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
