version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
    steps:
      - checkout

      - run:
          name: 'Setup virtual env'
          command: |
            python3 -mvenv /usr/local/share/virtualenvs/tap-amplitude
            source /usr/local/share/virtualenvs/tap-amplitude/bin/activate
            pip install -U 'pip==22.2.2' 'setuptools==65.3.0'
            pip install .[dev]

      #  Removed the "JSON Validator" step due to missing schema files

      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-amplitude/bin/activate
            pip install pylint
            pylint tap_amplitude -d C,R,W

      - add_ssh_keys

      - run:
          name: 'Unit Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-amplitude/bin/activate
            pip install nose coverage
            nosetests --with-coverage --cover-erase --cover-package=tap_amplitude --cover-html-dir=htmlcov tests/unittests
            coverage html

      - store_test_results:
          path: test_output/report.xml

      - store_artifacts:
          path: htmlcov

      - add_ssh_keys

      - run:
          name: 'Integration Tests'
          no_output_timeout: 30m
          command: |
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/tap_tester_sandbox dev_env.sh
            source dev_env.sh
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            run-test --tap=tap-amplitude tests

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user

  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
